# Generated by Django 3.2.11 on 2022-02-11 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeapp', '0002_student_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='propic',
            field=models.ImageField(default='', upload_to='gallery'),
        ),
    ]
